In [110]:
import pandas as pd 
import numpy as np
df = pd.read_csv("C:/Users/pc/Downloads/dirty_cafe_sales.csv")
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [111]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")
df

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [112]:
df["total_spent"]= df['total_spent'].replace("ERROR",None)
df

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,None,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [113]:
df['total_spent'] = pd.to_numeric(df['total_spent'], errors='coerce')
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')
df['price_per_unit'] = pd.to_numeric(df['price_per_unit'], errors='coerce')

In [114]:
df['total_spent'] = df['total_spent'].fillna(df['quantity'] * df['price_per_unit'])
df

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3.0,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [115]:
df = df.drop(columns = "location")
df

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,2023-06-11
...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,2023-08-30
9996,TXN_9659401,NaN,3.0,NaN,3.0,Digital Wallet,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,2023-03-02
9998,TXN_7695629,Cookie,3.0,NaN,3.0,Digital Wallet,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,2023-11-07

In [119]:
df["transaction_date"] = df["transaction_date"].replace("ERROR",0)
df["transaction_date"] = pd.to_datetime(df["transaction_date"], errors='coerce')

In [131]:
df = df.dropna()
df.head(30)

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,2023-03-31
6,TXN_4433211,UNKNOWN,3.0,3.0,9.0,ERROR,2023-10-06
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,2023-10-28
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,2023-11-07
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,2023-05-03
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,2023-11-15
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,2023-02-24
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,2023-03-25
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,2023-01-15
21,TXN_3567645,Smoothie,4.0,4.0,16.0,Credit Card,2023-03-30
22,TXN_5132361,Sandwich,3.0,4.0,12.0,Digital Wallet,2023-12-01
24,TXN_9400181,Sandwich,5.0,4.0,20.0,Cash,2023-06-03
25,TXN_7958992,Smoothie,3.0,4.0,12.0,UNKNOWN,2023-12-13
26,TXN_5183041,Cookie,5.0,1.0,5.0,Credit Card,2023-04-20
27,TXN_5695074,Juice,4.0,3.0,12.0,Credit Card,2023-04-10
28,TXN_8467949,Smoothie,5.0,4.0,20.0,Credit Card,2023-03-11
31,TXN_8927252,UNKNOWN,2.0,1.0,2.0,Credit Card,2023-11-06
34,TXN_8853997,Smoothie,2.0,4.0,8.0,Digital Wallet,2023-10-09
35,TXN_9130559,Sandwich,1.0,4.0,4.0,Credit Card,2023-05-28
37,TXN_1080432,Salad,2.0,5.0,10.0,Credit Card,2023-04-29
39,TXN_6688524,Coffee,4.0,2.0,8.0,ERROR,2023-06-29
45,TXN_5455792,Salad,3.0,5.0,15.0,Cash,2023-03-22
46,TXN_8078640,Juice,4.0,3.0,12.0,Digital Wallet,2023-11-03
48,TXN_8201146,Juice,5.0,3.0,15.0,Cash,2023-06-26
51,TXN_6342161,Salad,5.0,5.0,25.0,ERROR,2023-01-08

In [132]:
df.to_csv("C:/Users/pc/Desktop/Python/Jupyter_projects.csv")