## Ordianl and Label encoding

. use ordinal encoding when data follows an order or ranking like bad < average < good   , can be used for both input and output features

. use label encoding only for only y feature lable encoding is used for nominal data which dosent follow any order or ranking

In [3]:
import pandas as pd 
data = pd.read_csv(r"C:\Users\pc\Downloads\customer.csv")
data.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [49]:
from sklearn.preprocessing import OrdinalEncoder
od = OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])
data_scaled = od.fit_transform(data[["review","education"]])
data[["review","education"]] = data_scaled

In [50]:
data.head()

   age  gender  review  education purchased
0   30  Female     1.0        0.0        No
1   68  Female     0.0        1.0        No
2   70  Female     2.0        2.0        No
3   72  Female     2.0        2.0        No
4   16  Female     1.0        1.0        No

In [51]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["purchased"] = le.fit_transform(data["purchased"])
data.head()

   age  gender  review  education  purchased
0   30  Female     1.0        0.0          0
1   68  Female     0.0        1.0          0
2   70  Female     2.0        2.0          0
3   72  Female     2.0        2.0          0
4   16  Female     1.0        1.0          0

In [64]:
data["review"].value_counts()

review
0.0    18
2.0    18
1.0    14
Name: count, dtype: int64

## Nominal - One hot encoding

.its a type of nominal encoding where each unique value  in a row becomes a column and on the basis its presenece in a row we assign " One " to it the columns made from the values are called dummy columns

.if we include all the dummy columns it will create perfect multicolinearity meaning one variable can be predicted from the others to avoid that we remove one column to avoid it

In [19]:
df = pd.read_csv(r"C:\Users\pc\Downloads\cars.csv")
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [20]:
df.shape

(8128, 5)

In [26]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
oe = OneHotEncoder(drop="first", sparse_output = False)
encoded = oe.fit_transform(df[["fuel","owner"]])
pd.DataFrame(encoded)

        0    1    2    3    4    5    6
0     1.0  0.0  0.0  0.0  0.0  0.0  0.0
1     1.0  0.0  0.0  0.0  1.0  0.0  0.0
2     0.0  0.0  1.0  0.0  0.0  0.0  1.0
3     1.0  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  1.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...
8123  0.0  0.0  1.0  0.0  0.0  0.0  0.0
8124  1.0  0.0  0.0  1.0  0.0  0.0  0.0
8125  1.0  0.0  0.0  0.0  0.0  0.0  0.0
8126  1.0  0.0  0.0  0.0  0.0  0.0  0.0
8127  1.0  0.0  0.0  0.0  0.0  0.0  0.0

[8128 rows x 7 columns]

In [24]:
np.hstack(df[["brand","km_driven"]])

array(['brand', 'km_driven'], dtype='<U9')

## a better way to apply all these encoding is to use Column transformer which is an efficient and faster way 
### . method    ColumnTransformer( Transformer = ( ( name , tranformer you want to use , [column name] ), remainder = 'passthrough' ))

In [31]:
import pandas as pd
dataf = pd.read_csv(r"C:\Users\pc\Downloads\covid_toy.csv")
dataf

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [32]:
dataf["cough"].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [3]:
# import nessecery libraries 
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

tranform = ColumnTransformer([("tf1",OrdinalEncoder(categories= [["Mild","Strong"]]),["cough"]),
                   ("tf2",OneHotEncoder(sparse_output = False),["city"]),
                   ("tf3",SimpleImputer(strategy= "most_frequent"),["fever"])],
                   remainder= 'passthrough')

In [34]:
tranformed_data = pd.DataFrame(tranform.fit_transform(dataf))
tranformed_data

      0    1    2    3    4      5   6       7    8
0   0.0  0.0  0.0  1.0  0.0  103.0  60    Male   No
1   0.0  0.0  1.0  0.0  0.0  100.0  27    Male  Yes
2   0.0  0.0  1.0  0.0  0.0  101.0  42    Male   No
3   0.0  0.0  0.0  1.0  0.0   98.0  31  Female   No
4   0.0  0.0  0.0  0.0  1.0  101.0  65  Female   No
..  ...  ...  ...  ...  ...    ...  ..     ...  ...
95  0.0  1.0  0.0  0.0  0.0  104.0  12  Female   No
96  1.0  0.0  0.0  1.0  0.0  101.0  51  Female  Yes
97  0.0  1.0  0.0  0.0  0.0  101.0  20  Female   No
98  1.0  0.0  0.0  0.0  1.0   98.0   5  Female   No
99  1.0  0.0  0.0  1.0  0.0   98.0  10  Female  Yes

[100 rows x 9 columns]