In [34]:
import pandas as pd 
df = pd.read_csv("C:\\Users\\pc\\Desktop\\Python\\Jupyter_projects.csv")
df

,Unnamed: 0,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,transaction_date
0,0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,2023-09-08
1,1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,2023-05-16
2,2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,2023-07-19
3,3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,2023-04-27
4,4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,2023-06-11
...,...,...,...,...,...,...,...,...
6197,9991,TXN_3897619,Sandwich,3.0,4.0,12.0,Cash,2023-02-24
6198,9992,TXN_2739140,Smoothie,4.0,4.0,16.0,UNKNOWN,2023-07-05
6199,9993,TXN_4766549,Smoothie,2.0,4.0,8.0,Cash,2023-10-20
6200,9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,2023-03-02
6201,9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,2023-11-07

In [35]:
df = df.drop(df.index[101 : 6999])
df = df.drop(columns = ['Unnamed: 0','transaction_date'])
df

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet
...,...,...,...,...,...,...
96,TXN_1648671,Sandwich,3.0,4.0,12.0,Cash
97,TXN_4062737,Cake,3.0,3.0,9.0,Cash
98,TXN_9249507,Cookie,4.0,1.0,4.0,Credit Card
99,TXN_9836934,Cookie,3.0,1.0,3.0,Digital Wallet
100,TXN_3925836,Cookie,3.0,1.0,3.0,Digital Wallet

In [39]:
group_by = df.groupby('item')
group_by.mean(numeric_only = True)

          quantity  price_per_unit  total_spent
item
Cake      3.200000            3.00     9.600000
Coffee    3.200000            2.00     6.400000
Cookie    3.444444            1.00     3.444444
ERROR     3.000000            4.00    10.000000
Juice     3.529412            3.00    10.588235
Salad     3.500000            5.00    17.500000
Sandwich  2.900000            4.00    11.600000
Smoothie  3.545455            4.00    14.181818
Tea       3.222222            1.50     4.833333
UNKNOWN   3.750000            3.25    14.000000

In [40]:
group_by.count()

,transaction_id,quantity,price_per_unit,total_spent,payment_method
item,,,,,
Cake,10,10,10,10,10
Coffee,15,15,15,15,15
Cookie,9,9,9,9,9
ERROR,2,2,2,2,2
Juice,17,17,17,17,17
Salad,14,14,14,14,14
Sandwich,10,10,10,10,10
Smoothie,11,11,11,11,11
Tea,9,9,9,9,9
UNKNOWN,4,4,4,4,4

In [44]:
group_by.min()

         transaction_id  quantity  price_per_unit  total_spent  payment_method
item
Cake        TXN_4062737       2.0             3.0          6.0            Cash
Coffee      TXN_1928241       1.0             2.0          2.0            Cash
Cookie      TXN_3068204       1.0             1.0          1.0     Credit Card
ERROR       TXN_8471743       1.0             3.0          5.0  Digital Wallet
Juice       TXN_1150033       1.0             3.0          3.0            Cash
Salad       TXN_1080432       2.0             5.0         10.0            Cash
Sandwich    TXN_1648671       1.0             4.0          4.0            Cash
Smoothie    TXN_1900620       2.0             4.0          8.0     Credit Card
Tea         TXN_2277042       1.0             1.5          1.5            Cash
UNKNOWN     TXN_3226832       2.0             1.0          2.0            Cash

In [42]:
group_by.max()

         transaction_id  quantity  price_per_unit  total_spent  payment_method
item
Cake        TXN_9790731       5.0             3.0         15.0         UNKNOWN
Coffee      TXN_8779771       5.0             2.0         10.0           ERROR
Cookie      TXN_9836934       5.0             1.0          5.0  Digital Wallet
ERROR       TXN_9487821       5.0             5.0         15.0  Digital Wallet
Juice       TXN_9999113       5.0             3.0         15.0  Digital Wallet
Salad       TXN_8687151       5.0             5.0         25.0         UNKNOWN
Sandwich    TXN_9400181       5.0             4.0         20.0  Digital Wallet
Smoothie    TXN_9230615       5.0             4.0         20.0         UNKNOWN
Tea         TXN_8976658       5.0             1.5          7.5         UNKNOWN
UNKNOWN     TXN_8927252       5.0             5.0         25.0           ERROR

In [47]:
group_by.sum(numeric_only = True)

          quantity  price_per_unit  total_spent
item
Cake          32.0            30.0         96.0
Coffee        48.0            30.0         96.0
Cookie        31.0             9.0         31.0
ERROR          6.0             8.0         20.0
Juice         60.0            51.0        180.0
Salad         49.0            70.0        245.0
Sandwich      29.0            40.0        116.0
Smoothie      39.0            44.0        156.0
Tea           29.0            13.5         43.5
UNKNOWN       15.0            13.0         56.0

In [51]:
group_by.agg({"quantity" : ['mean','min','max','count','sum'],'price_per_unit':['mean','min','max','count','sum']})

          quantity                       price_per_unit
              mean  min  max count   sum           mean  min  max count   sum
item
Cake      3.200000  2.0  5.0    10  32.0           3.00  3.0  3.0    10  30.0
Coffee    3.200000  1.0  5.0    15  48.0           2.00  2.0  2.0    15  30.0
Cookie    3.444444  1.0  5.0     9  31.0           1.00  1.0  1.0     9   9.0
ERROR     3.000000  1.0  5.0     2   6.0           4.00  3.0  5.0     2   8.0
Juice     3.529412  1.0  5.0    17  60.0           3.00  3.0  3.0    17  51.0
Salad     3.500000  2.0  5.0    14  49.0           5.00  5.0  5.0    14  70.0
Sandwich  2.900000  1.0  5.0    10  29.0           4.00  4.0  4.0    10  40.0
Smoothie  3.545455  2.0  5.0    11  39.0           4.00  4.0  4.0    11  44.0
Tea       3.222222  1.0  5.0     9  29.0           1.50  1.5  1.5     9  13.5
UNKNOWN   3.750000  2.0  5.0     4  15.0           3.25  1.0  5.0     4  13.0

In [57]:
df.groupby(['quantity','total_spent']).mean(numeric_only = True)

                      price_per_unit
quantity total_spent
1.0      1.0                     1.0
         1.5                     1.5
         2.0                     2.0
         3.0                     3.0
         4.0                     4.0
         5.0                     5.0
2.0      2.0                     1.0
         3.0                     1.5
         4.0                     2.0
         6.0                     3.0
         8.0                     4.0
         10.0                    5.0
3.0      3.0                     1.0
         6.0                     2.0
         9.0                     3.0
         12.0                    4.0
         15.0                    5.0
4.0      4.0                     1.0
         6.0                     1.5
         8.0                     2.0
         12.0                    3.0
         16.0                    4.0
         20.0                    5.0
5.0      5.0                     1.0
         7.5                     1.5
         10.0                    2.0
         15.0                    3.0
         20.0                    4.0
         25.0                    5.0

In [58]:
df.groupby(['quantity','total_spent']).agg({'price_per_unit':['mean','min','max','count','sum']})

                     price_per_unit
                               mean  min  max count   sum
quantity total_spent
1.0      1.0                    1.0  1.0  1.0     1   1.0
         1.5                    1.5  1.5  1.5     2   3.0
         2.0                    2.0  2.0  2.0     2   4.0
         3.0                    3.0  3.0  3.0     1   3.0
         4.0                    4.0  4.0  4.0     2   8.0
         5.0                    5.0  5.0  5.0     1   5.0
2.0      2.0                    1.0  1.0  1.0     1   1.0
         3.0                    1.5  1.5  1.5     2   3.0
         4.0                    2.0  2.0  2.0     4   8.0
         6.0                    3.0  3.0  3.0     7  21.0
         8.0                    4.0  4.0  4.0     5  20.0
         10.0                   5.0  5.0  5.0     4  20.0
3.0      3.0                    1.0  1.0  1.0     4   4.0
         6.0                    2.0  2.0  2.0     2   4.0
         9.0                    3.0  3.0  3.0     6  18.0
         12.0                   4.0  4.0  4.0     4  16.0
         15.0                   5.0  5.0  5.0     4  20.0
4.0      4.0                    1.0  1.0  1.0     2   2.0
         6.0                    1.5  1.5  1.5     2   3.0
         8.0                    2.0  2.0  2.0     3   6.0
         12.0                   3.0  3.0  3.0     8  24.0
         16.0                   4.0  4.0  4.0     6  24.0
         20.0                   5.0  5.0  5.0     1   5.0
5.0      5.0                    1.0  1.0  1.0     2   2.0
         7.5                    1.5  1.5  1.5     3   4.5
         10.0                   2.0  2.0  2.0     4   8.0
         15.0                   3.0  3.0  3.0     7  21.0
         20.0                   4.0  4.0  4.0     5  20.0
         25.0                   5.0  5.0  5.0     6  30.0