In [10]:
# working with csv
import pandas as pd
data = pd.read_csv(r"C:\Users\pc\Downloads\heart.csv",index_col = ['age'],chunksize=200)

for chunks in data:
    print(chunks.shape)

(200, 13)
(200, 13)
(200, 13)
(200, 13)
(200, 13)
(25, 13)

In [ ]:
#working with json
df = pd.read_json(r"C:\Users\pc\Downloads\US_STATE_recipes.json")
df

,0,1,2,3,4,5,6,7,8,9,...,3753,3754,3755,3756,3757,3758,3759,3760,3761,3762
Contient,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,...,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa,Africa
Country_State,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
cuisine,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,Missouri,...,Montana,Montana,Montana,Montana,Montana,Montana,Montana,Montana,Montana,Montana
title,Ground Beef and Cabbage,Old Fashioned Peach Cobbler,St. Louis Toasted Ravioli,Amish Friendship Bread Starter,Simple Fried Morel Mushrooms,Big Al's K.C. Bar-B-Q Sauce,Lemon Zucchini Bread,Springfield Style Cashew Chicken I,Kansas City Ice Water,St. Louis Pork Steaks,...,The Humble Shepherd,Easy Slow Cooker Venison Stew,Fennel in Wine and Honey,Spinach and Goat Cheese Salad with Beetroot Vi...,Montana Russian Black Bread,Cracked Black Venison,Montana Spicy Bison Dip,Grandpa Mack's Fifth-Generation Pancake Recipe,Couscous with Dried Cherries,Jo's Mountain Mush
URL,https://www.allrecipes.com/recipe/229324/groun...,https://www.allrecipes.com/recipe/19897/old-fa...,https://www.allrecipes.com/recipe/16907/st-lou...,https://www.allrecipes.com/recipe/7063/amish-f...,https://www.allrecipes.com/recipe/220833/simpl...,https://www.allrecipes.com/recipe/44491/big-al...,https://www.allrecipes.com/recipe/58817/lemon-...,https://www.allrecipes.com/recipe/9009/springf...,https://www.allrecipes.com/recipe/51923/kansas...,https://www.allrecipes.com/recipe/73669/st-lou...,...,https://www.allrecipes.com/recipe/76519/the-hu...,https://www.allrecipes.com/recipe/32081/easy-s...,https://www.allrecipes.com/recipe/95546/fennel...,https://www.allrecipes.com/recipe/46492/spinac...,https://www.allrecipes.com/recipe/236547/monta...,https://www.allrecipes.com/recipe/18774/cracke...,https://www.allrecipes.com/recipe/256810/monta...,https://www.allrecipes.com/recipe/279565/grand...,https://www.allrecipes.com/recipe/18273/cousco...,https://www.allrecipes.com/recipe/21272/jos-mo...
rating,4.5,4.6,4.5,4.7,4.7,4.8,4.6,4.4,4.5,4.0,...,4.4,4.5,4.1,4.7,4.0,4.4,4.3,3.7,4.2,4.3
total_time,60,130,25,14440,30,35,60,35,2,35,...,80,490,60,30,215,70,25,25,20,25
prep_time,15,30,15,30,20,15,15,15,2,10,...,30,10,15,25,20,10,10,5,5,10
cook_time,45,70,10,None,10,20,45,20,None,25,...,50,480,45,5,45,60,15,20,10,15
description,This ground beef and cabbage recipe combines l...,This old-fashioned peach cobbler recipe featur...,Toasted ravioli traces its roots to St. Louis....,Amish friendship bread starter is made with ye...,"The rich, meaty flavor of fresh morel mushroom...",This is a Kansas City-style BBQ sauce recipe s...,Lemon zest adds a touch of summer to this swee...,Fried chicken is topped with an Asian-style mi...,Citrus flavors are blended with gin and vodka....,Grilled pork steaks are juicy and tender in th...,...,A twist on the original shepherd's pie using g...,An easy slow cooker stew made with venison and...,"A great side dish for fennel lovers, originall...",A beet vinaigrette is drizzled over baby spina...,"Black bread, made with dark beer, coffee, mola...","Tasty and spicy, this is a simple venison stea...",Kick off game day with this touchdown-worthy M...,This family-favorite pancake recipe has been s...,My family loves couscous and this fruity varia...,"A jumbled, filling breakfast created when I wa..."
ingredients,"[1 large head cabbage, finely chopped, 1 (14.5...","[2.5 cups all-purpose flour, 4 tablespoons whi...","[1 (16 ounce) jar marinara sauce, 1 large egg,...","[1 (.25 ounce) package active dry yeast, 0.25 ...",[1 pound fresh morel mushrooms - dirt gently b...,"[2 cups ketchup, 2 cups tomato sauce, 1.25 cup...","[1.5 cups shredded zucchini, 0.75 cup white su...","[4 skinless, boneless chicken breasts, 2 cups ...","[1 fluid ounce gin, 1 fluid ounce vodka, 0.5 f...","[5 pork shoulder steaks, 0.125 teaspoon season...",...,"[cooking spray, 1.5 pounds russet potatoes, pe...","[2 pounds venison stew meat, 1 (10.75 ounce) c...","[4 fennel bulbs, trimmed and quartered, 0.25 c...","[1 cup walnuts, coarsely chopped, 2 tablespoon...","[2.5 cups whole wheat bread flour, 1 cup rye f...","[2 (1/2 pound) venison steaks, 2 teaspoons cra...","[1 pound ground bison, 0.5 cup chopped onion, ...","[2 cups all-purpose flour, 2 tablespoons white...","[1 cup chicken broth, 0.25 cup water, 0.25 cup...","[8 beef frankfurters, 3 red potatoes, cubed, 2..."
instructions,"[Place cabbage, tomatoes with juice, onion, It...","[Make crust: Sift together flour, 3 tablespoon...",[Heat marinara sauce in a saucepan over medium...,[Dissolve yeast in warm water in a small bowl;...,[Place halved morel mushrooms in a large bowl;...,"[Mix together ketchup, tomato sauce, brown sug...",[Preheat oven to 325 degrees F (165 degrees C)...,[Cut the chicken breasts into 1 inch pieces. I...,"[Combine the gin, vodka, lime juice, and tripl...",[Preheat an outdoor grill for medium-low heat ...,...,[Preheat an oven to 350 degrees F (175 degrees...,"[In a slow cooker, combine venison, cream of m...",[Place the fennel quarters in large deep skill...,"[In small saucepan over medium heat, cook and ...","[Place whole wheat bread flour, rye flour, coc...",[Season venison steaks with pepper and salt. M...,[Brown meat and onion in large skillet on medi...,"[Mix flour, sugar, baking powder, and salt tog...","[In a 2 quart saucepan, combine chicken broth,...",[Coat a large skillet with non-stick cooking s...
nutrients,"{'calories': '228 kcal', 'carbohydrateContent'...","{'calories': '338 kcal', 'carbohydrateContent'...","{'calories': '374 kcal', 'carbohydrateContent'...","{'calories': '34 kcal', 'carbohydrateContent':...","{'calories': '185 kcal', 'carbohydrateContent'...","{'calories': '46 kcal', 'carbohydrateContent':...","{'calories': '195 kcal', 'carbohydrateContent'...","{'calories': '652 kcal', 'carbohydrateContent'...",{},"{'calories': '517 kcal', 'carbohydrateContent'...",...,"{'calories': '567 kcal', 'carbohydrateContent'...","{'calories': '278 kcal', 'carbohydrateContent'...","{'calories': '133 kcal', 'carbohydrateContent'...","{'calories': '163 kcal', 'carbohydrateContent'...","{'calories': '241 kcal', 'carbohydrateContent'...","{'calories': '151 kcal', 'carbohydrateContent'...","{'calories': '98 kcal', 'carbohydrateContent':...","{'calories': '241 kcal', 'carbohydrateContent'...","{'calories': '243 kcal', 'carbohydrateContent'...","{'calories': '460 kcal', 'carbohydrateContent'..."
serves,6 servings,18 servings,6 servings,120 servings,4 servings,48 servings,12 servings,6 servings,1 serving,5 servings,...,6 servings,6 servings,8 servings,12 servings,10 servings,4 servings,20 servings,9 servings,4 servings,6 servings

In [22]:
data_tilted = df.T
data_tilted

,Contient,Country_State,cuisine,title,URL,rating,total_time,prep_time,cook_time,description,ingredients,instructions,nutrients,serves
0,Africa,None,Missouri,Ground Beef and Cabbage,https://www.allrecipes.com/recipe/229324/groun...,4.5,60,15,45,This ground beef and cabbage recipe combines l...,"[1 large head cabbage, finely chopped, 1 (14.5...","[Place cabbage, tomatoes with juice, onion, It...","{'calories': '228 kcal', 'carbohydrateContent'...",6 servings
1,Africa,None,Missouri,Old Fashioned Peach Cobbler,https://www.allrecipes.com/recipe/19897/old-fa...,4.6,130,30,70,This old-fashioned peach cobbler recipe featur...,"[2.5 cups all-purpose flour, 4 tablespoons whi...","[Make crust: Sift together flour, 3 tablespoon...","{'calories': '338 kcal', 'carbohydrateContent'...",18 servings
2,Africa,None,Missouri,St. Louis Toasted Ravioli,https://www.allrecipes.com/recipe/16907/st-lou...,4.5,25,15,10,Toasted ravioli traces its roots to St. Louis....,"[1 (16 ounce) jar marinara sauce, 1 large egg,...",[Heat marinara sauce in a saucepan over medium...,"{'calories': '374 kcal', 'carbohydrateContent'...",6 servings
3,Africa,None,Missouri,Amish Friendship Bread Starter,https://www.allrecipes.com/recipe/7063/amish-f...,4.7,14440,30,None,Amish friendship bread starter is made with ye...,"[1 (.25 ounce) package active dry yeast, 0.25 ...",[Dissolve yeast in warm water in a small bowl;...,"{'calories': '34 kcal', 'carbohydrateContent':...",120 servings
4,Africa,None,Missouri,Simple Fried Morel Mushrooms,https://www.allrecipes.com/recipe/220833/simpl...,4.7,30,20,10,"The rich, meaty flavor of fresh morel mushroom...",[1 pound fresh morel mushrooms - dirt gently b...,[Place halved morel mushrooms in a large bowl;...,"{'calories': '185 kcal', 'carbohydrateContent'...",4 servings
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3758,Africa,None,Montana,Cracked Black Venison,https://www.allrecipes.com/recipe/18774/cracke...,4.4,70,10,60,"Tasty and spicy, this is a simple venison stea...","[2 (1/2 pound) venison steaks, 2 teaspoons cra...",[Season venison steaks with pepper and salt. M...,"{'calories': '151 kcal', 'carbohydrateContent'...",4 servings
3759,Africa,None,Montana,Montana Spicy Bison Dip,https://www.allrecipes.com/recipe/256810/monta...,4.3,25,10,15,Kick off game day with this touchdown-worthy M...,"[1 pound ground bison, 0.5 cup chopped onion, ...",[Brown meat and onion in large skillet on medi...,"{'calories': '98 kcal', 'carbohydrateContent':...",20 servings
3760,Africa,None,Montana,Grandpa Mack's Fifth-Generation Pancake Recipe,https://www.allrecipes.com/recipe/279565/grand...,3.7,25,5,20,This family-favorite pancake recipe has been s...,"[2 cups all-purpose flour, 2 tablespoons white...","[Mix flour, sugar, baking powder, and salt tog...","{'calories': '241 kcal', 'carbohydrateContent'...",9 servings
3761,Africa,None,Montana,Couscous with Dried Cherries,https://www.allrecipes.com/recipe/18273/cousco...,4.2,20,5,10,My family loves couscous and this fruity varia...,"[1 cup chicken broth, 0.25 cup water, 0.25 cup...","[In a 2 quart saucepan, combine chicken broth,...","{'calories': '243 kcal', 'carbohydrateContent'...",4 servings
3762,Africa,None,Montana,Jo's Mountain Mush,https://www.allrecipes.com/recipe/21272/jos-mo...,4.3,25,10,15,"A jumbled, filling breakfast created when I wa...","[8 beef frankfurters, 3 red potatoes, cubed, 2...",[Coat a large skillet with non-stick cooking s...,"{'calories': '460 kcal', 'carbohydrateContent'...",6 servings

In [ ]:
#working with mysql files
import mysql.connector

In [43]:
conn = mysql.connector.connect(host = 'localhost',user = 'root',password ='',database = 'world')

In [44]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'PAK'",conn).head()

C:\Users\pc\AppData\Local\Temp\ipykernel_2288\901719170.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'PAK'",conn).head()

     ID        Name CountryCode District  Population
0  2822     Karachi         PAK    Sindh     9269265
1  2823      Lahore         PAK   Punjab     5063499
2  2824  Faisalabad         PAK   Punjab     1977246
3  2825  Rawalpindi         PAK   Punjab     1406214
4  2826      Multan         PAK   Punjab     1182441

In [46]:
pd.read_sql_query("SELECT * FROM country WHERE LifeExpectancy > 50",conn)

C:\Users\pc\AppData\Local\Temp\ipykernel_2288\4050581254.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM country WHERE LifeExpectancy > 50",conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129,AW
1,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62,AI
2,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34,AL
3,AND,Andorra,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,,55,AD
4,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33,AN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,VUT,Vanuatu,Oceania,Melanesia,12189.0,1980.0,190000,60.6,261.0,246.0,Vanuatu,Republic,John Bani,3537,VU
190,WSM,Samoa,Oceania,Polynesia,2831.0,1962.0,180000,69.2,141.0,157.0,Samoa,Parlementary Monarchy,Malietoa Tanumafili II,3169,WS
191,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780,YE
192,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792,YU
193,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716,ZA

In [47]:
pd.read_sql_query("SELECT * FROM countrylanguage",conn)

C:\Users\pc\AppData\Local\Temp\ipykernel_2288\4078718901.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM countrylanguage",conn)

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]

In [4]:
# for API

import requests

request = requests.get('https://jsonplaceholder.typicode.com/posts').json()
pd.DataFrame(request)[['id','title']]

     id                                              title
0     1  sunt aut facere repellat provident occaecati e...
1     2                                       qui est esse
2     3  ea molestias quasi exercitationem repellat qui...
3     4                               eum et est occaecati
4     5                                 nesciunt quas odio
..  ...                                                ...
95   96  quaerat velit veniam amet cupiditate aut numqu...
96   97         quas fugiat ut perspiciatis vero provident
97   98                        laboriosam dolor voluptates
98   99  temporibus sit alias delectus eligendi possimu...
99  100              at nam consequatur ea labore ea harum

[100 rows x 2 columns]

In [1]:
# webscrapping

import pandas as pd 
import requests
from bs4 import BeautifulSoup

web_page = requests.get('https://books.toscrape.com/')
soup = BeautifulSoup(web_page.text,'lxml')

In [ ]:
# Title

soup.find_all('h3')

In [ ]:
for i in soup.find_all('h3'):
    print(i.text)

In [ ]:
# for stocks
soup.find_all('p',class_='instock')

In [ ]:
# price

price = soup.find_all('p',class_="price_color")
for p in price:
    print(p.text.strip('Â'))

In [188]:
title = []
price = []
rating = []
stock = []

col = soup.find_all("article", class_="product_pod")

for index in col:
    title.append(index.find('h3').find("a")["title"])
    price.append(index.find('p',class_ = 'price_color').text.strip('Â'))
    rating.append(index.find('p',class_ = 'star-rating')["class"][1])
    stock.append(index.find('p',class_ = 'instock').text.strip())

In [189]:
print("Titles:", title)
print("Prices:", price)
print("Ratings:", rating)
print("stock:", stock)

Titles: ['A Light in the Attic', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History of Humankind', 'The Requiem Red', 'The Dirty Little Secrets of Getting Your Dream Job', 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 'The Black Maria', 'Starving Hearts (Triangular Trade Trilogy, #1)', "Shakespeare's Sonnets", 'Set Me Free', "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 'Rip it Up and Start Again', 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 'Olio', 'Mesaerion: The Best Science Fiction Stories 1800-1849', 'Libertarianism for Beginners', "It's Only the Himalayas"]
Prices: ['£51.77', '£53.74', '£50.10', '£47.82', '£54.23', '£22.65', '£33.34', '£17.93', '£22.60', '£52.15', '£13.99', '£20.66', '£17.46', '£52.29', '£35.02', '£57.25', '£23.88', '£37.59', '£51.33', '£45.17']
Ratings: ['Three', 'One', 'One', 'Four', 'Five', 'One', 'Four', 'Three', 'Four', 'One', 'Two', 'Four', 'Five', 'Five', 'Five', 'Three', 'One', 'One', 'Two', 'Two']
stock: ['In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock']

In [193]:
# creating dataframe
import pandas as pd

data = {"Title":title,"Prices":price,"Ratings":rating,"stock":stock}
df = pd.DataFrame(data)
df

,Title,Prices,Ratings,stock
0,A Light in the Attic,£51.77,Three,In stock
1,Tipping the Velvet,£53.74,One,In stock
2,Soumission,£50.10,One,In stock
3,Sharp Objects,£47.82,Four,In stock
4,Sapiens: A Brief History of Humankind,£54.23,Five,In stock
5,The Requiem Red,£22.65,One,In stock
6,The Dirty Little Secrets of Getting Your Dream...,£33.34,Four,In stock
7,The Coming Woman: A Novel Based on the Life of...,£17.93,Three,In stock
8,The Boys in the Boat: Nine Americans and Their...,£22.60,Four,In stock
9,The Black Maria,£52.15,One,In stock
10,"Starving Hearts (Triangular Trade Trilogy, #1)",£13.99,Two,In stock
11,Shakespeare's Sonnets,£20.66,Four,In stock
12,Set Me Free,£17.46,Five,In stock
13,Scott Pilgrim's Precious Little Life (Scott Pi...,£52.29,Five,In stock
14,Rip it Up and Start Again,£35.02,Five,In stock
15,Our Band Could Be Your Life: Scenes from the A...,£57.25,Three,In stock
16,Olio,£23.88,One,In stock
17,Mesaerion: The Best Science Fiction Stories 18...,£37.59,One,In stock
18,Libertarianism for Beginners,£51.33,Two,In stock
19,It's Only the Himalayas,£45.17,Two,In stock

In [ ]:
title = []
price = []
rating = []
stock = []

for page in range(1,51):
    web_page = requests.get(f'https://books.toscrape.com/catalogue/page-{page}.html')
    soup = BeautifulSoup(web_page.text,'lxml')
    pages = soup.find("article", class_="product_pod")
    
    col = soup.find_all("article", class_="product_pod")

    for index in col:
        title.append(index.find('h3').find("a")["title"])
        price.append(index.find('p',class_ = 'price_color').text.strip('Â'))
        rating.append(index.find('p',class_ = 'star-rating')["class"][1])
        stock.append(index.find('p',class_ = 'instock').text.strip())

In [3]:
print("Titles:", title)
print("Prices:", price)
print("Ratings:", rating)
print("stock:", stock)

Titles: ['A Light in the Attic', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History of Humankind', 'The Requiem Red', 'The Dirty Little Secrets of Getting Your Dream Job', 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 'The Black Maria', 'Starving Hearts (Triangular Trade Trilogy, #1)', "Shakespeare's Sonnets", 'Set Me Free', "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 'Rip it Up and Start Again', 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 'Olio', 'Mesaerion: The Best Science Fiction Stories 1800-1849', 'Libertarianism for Beginners', "It's Only the Himalayas", 'In Her Wake', 'How Music Works', 'Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More', 'Chase Me (Paris Nights #2)', 'Black Dust', 'Birdsong: A Story in Pictures', "America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana", 'Aladdin and His Wonderful Lamp', 'Worlds Elsewhere: Journeys Around Shakespeareâ\x80\x99s Globe', 'Wall and Piece', 'The Four Agreements: A Practical Guide to Personal Freedom', 'The Five Love Languages: How to Express Heartfelt Commitment to Your Mate', 'The Elephant Tree', 'The Bear and the Piano', "Sophie's World", 'Penny Maybe', 'Maude (1883-1993):She Grew Up with the country', 'In a Dark, Dark Wood', 'Behind Closed Doors', "You can't bury them all: Poems", 'Slow States of Collapse: Poems', 'Reasons to Stay Alive', 'Private Paris (Private #10)', '#HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.', 'Without Borders (Wanderlove #1)', 'When We Collided', 'We Love You, Charlie Freeman', 'Untitled Collection: Sabbath Poems 2014', 'Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness', 'Unicorn Tracks', 'Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink', 'Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRoNiCLE #2)', 'Throwing Rocks at the Google Bus: How Growth Became the Enemy of Prosperity', 'This One Summer', 'Thirst', 'The Torch Is Passed: A Harding Family Story', 'The Secret of Dreadwillow Carse', 'The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!', 'The Past Never Ends', 'The Natural History of Us (The Fine Art of Pretending #2)', 'The Nameless City (The Nameless City #1)', 'The Murder That Never Was (Forensic Instincts #5)', "The Most Perfect Thing: Inside (and Outside) a Bird's Egg", 'The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy', 'The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing', 'The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer', 'The Gutsy Girl: Escapades for Your Life of Epic Adventure', 'The Electric Pencil: Drawings from Inside State Hospital No. 3', 'The Death of Humanity: and the Case for Life', 'The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life', 'The Art Forger', 'The Age of Genius: The Seventeenth Century and the Birth of the Modern Mind', "The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution", 'Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up', 'Soul Reader', 'Security', 'Saga, Volume 6 (Saga (Collected Editions) #6)', 'Saga, Volume 5 (Saga (Collected Editions) #5)', 'Reskilling America: Learning to Labor in the Twenty-First Century', 'Rat Queens, Vol. 3: Demons (Rat Queens (Collected Editions) #11-15)', 'Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)', 'Princess Between Worlds (Wide-Awake Princess #5)', 'Pop Gun War, Volume 1: Gift', 'Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics', 'Patience', 'Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)', 'orange: The Complete Collection 1 (orange: The Complete Collection #1)', 'Online Marketing for Busy Authors: A Step-By-Step Guide', 'On a Midnight Clear', 'Obsidian (Lux #1)', 'My Paris Kitchen: Recipes and Stories', 'Masks and Shadows', 'Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed', 'Lumberjanes, Vol. 2: Friendship to the Max (Lumberjanes #5-8)', 'Lumberjanes, Vol. 1: Beware the Kitten Holy (Lumberjanes #1-4)', 'Lumberjanes Vol. 3: A Terrible Plan (Lumberjanes #9-12)', 'Layered: Baking, Building, and Styling Spectacular Cakes', 'Judo: Seven Steps to Black Belt (an Introductory Guide for Beginners)', 'Join', 'In the Country We Love: My Family Divided', 'Immunity: How Elie Metchnikoff Changed the Course of Modern Medicine', 'I Hate Fairyland, Vol. 1: Madly Ever After (I Hate Fairyland (Compilations) #1-5)', 'I am a Hero Omnibus Volume 1', 'How to Be Miserable: 40 Strategies You Already Use', 'Her Backup Boyfriend (The Sorensen Family #1)', 'Giant Days, Vol. 2 (Giant Days #5-8)', 'Forever and Forever: The Courtship of Henry Longfellow and Fanny Appleton', 'First and First (Five Boroughs #3)', 'Fifty Shades Darker (Fifty Shades #2)', 'Everydata: The Misinformation Hidden in the Little Data You Consume Every Day', "Don't Be a Jerk: And Other Practical Advice from Dogen, Japan's Greatest Zen Master", 'Danganronpa Volume 1', 'Crown of Midnight (Throne of Glass #2)', 'Codename Baboushka, Volume 1: The Conclave of Death', 'Camp Midnight', 'Call the Nurse: True Stories of a Country Nurse on a Scottish Isle', 'Burning', 'Bossypants', 'Bitch Planet, Vol. 1: Extraordinary Machine (Bitch Planet (Collected Editions))', 'Avatar: The Last Airbender: Smoke and Shadow, Part 3 (Smoke and Shadow #3)', 'Algorithms to Live By: The Computer Science of Human Decisions', 'A World of Flavor: Your Gluten Free Passport', 'A Piece of Sky, a Grain of Rice: A Memoir in Four Meditations', 'A Murder in Time', 'A Flight of Arrows (The Pathfinders #2)', 'A Fierce and Subtle Poison', 'A Court of Thorns and Roses (A Court of Thorns and Roses #1)', '(Un)Qualified: How God Uses Broken People to Do Big Things', 'You Are What You Love: The Spiritual Power of Habit', "William Shakespeare's Star Wars: Verily, A New Hope (William Shakespeare's Star Wars #4)", 'Tuesday Nights in 1980', 'Tracing Numbers on a Train', 'Throne of Glass (Throne of Glass #1)', 'Thomas Jefferson and the Tripoli Pirates: The Forgotten War That Changed American History', 'Thirteen Reasons Why', 'The White Cat and the Monk: A Retelling of the Poem â\x80\x9cPangur BÃ¡nâ\x80\x9d', 'The Wedding Dress', 'The Vacationers', 'The Third Wave: An Entrepreneurâ\x80\x99s Vision of the Future', 'The Stranger', 'The Shadow Hero (The Shadow Hero)', 'The Secret (The Secret #1)', 'The Regional Office Is Under Attack!', 'The Psychopath Test: A Journey Through the Madness Industry', 'The Project', 'The Power of Now: A Guide to Spiritual Enlightenment', "The Omnivore's Dilemma: A Natural History of Four Meals", 'The Nerdy Nummies Cookbook: Sweet Treats for the Geek in All of Us', 'The Murder of Roger Ackroyd (Hercule Poirot #4)', 'The Mistake (Off-Campus #2)', "The Matchmaker's Playbook (Wingmen Inc. #1)", 'The Love and Lemons Cookbook: An Apple-to-Zucchini Celebration of Impromptu Cooking', 'The Long Shadow of Small Ghosts: Murder and Memory in an American City', 'The Kite Runner', 'The House by the Lake', 'The Glittering Court (The Glittering Court #1)', 'The Girl on the Train', 'The Genius of Birds', 'The Emerald Mystery', 'The Cookies & Cups Cookbook: 125+ sweet & savory recipes reminding you to Always Eat Dessert First', "The Bridge to Consciousness: I'm Writing the Bridge Between Science and Our Old and New Beliefs.", "The Artist's Way: A Spiritual Path to Higher Creativity", 'The Art of War', 'The Argonauts', 'The 10% Entrepreneur: Live Your Startup Dream Without Quitting Your Day Job', 'Suddenly in Love (Lake Haven #1)', 'Something More Than This', 'Soft Apocalypse', "So You've Been Publicly Shamed", 'Shoe Dog: A Memoir by the Creator of NIKE', 'Shobu Samurai, Project Aryoku (#3)', 'Secrets and Lace (Fatal Hearts #1)', 'Scarlett Epstein Hates It Here', 'Romero and Juliet: A Tragic Tale of Love and Zombies', 'Redeeming Love', 'Poses for Artists Volume 1 - Dynamic and Sitting Poses: An Essential Reference for Figure Drawing and the Human Form', 'Poems That Make Grown Women Cry', 'Nightingale, Sing', 'Night Sky with Exit Wounds', 'Mrs. Houdini', 'Modern Romance', 'Miss Peregrineâ\x80\x99s Home for Peculiar Children (Miss Peregrineâ\x80\x99s Peculiar Children #1)', 'Louisa: The Extraordinary Life of Mrs. Adams', 'Little Red', 'Library of Souls (Miss Peregrineâ\x80\x99s Peculiar Children #3)', 'Large Print Heart of the Pride', 'I Had a Nice Time And Other Lies...: How to find love & sh*t like that', 'Hollow City (Miss Peregrineâ\x80\x99s Peculiar Children #2)', 'Grumbles', 'Full Moon over Noahâ\x80\x99s Ark: An Odyssey to Mount Ararat and Beyond', 'Frostbite (Vampire Academy #2)', 'Follow You Home', 'First Steps for New Christians (Print Edition)', 'Finders Keepers (Bill Hodges Trilogy #2)', 'Fables, Vol. 1: Legends in Exile (Fables #1)', 'Eureka Trivia 6.0', 'Drive: The Surprising Truth About What Motivates Us', 'Done Rubbed Out (Reightman & Bailey #1)', 'Doing It Over (Most Likely To #1)', 'Deliciously Ella Every Day: Quick and Easy Recipes for Gluten-Free Snacks, Packed Lunches, and Simple Meals', 'Dark Notes', 'Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead', 'Close to You', 'Chasing Heaven: What Dying Taught Me About Living', 'Big Magic: Creative Living Beyond Fear', 'Becoming Wise: An Inquiry into the Mystery and Art of Living', 'Beauty Restored (Riley Family Legacy Novellas #3)', 'Batman: The Long Halloween (Batman)', 'Batman: The Dark Knight Returns (Batman)', "Ayumi's Violin", 'Anonymous', 'Amy Meets the Saints and Sages', 'Amid the Chaos', 'Amatus', 'Agnostic: A Spirited Manifesto', 'Zealot: The Life and Times of Jesus of Nazareth', 'You (You #1)', 'Wonder Woman: Earth One, Volume One (Wonder Woman: Earth One #1)', 'Wild Swans', 'Why the Right Went Wrong: Conservatism--From Goldwater to the Tea Party and Beyond', 'Whole Lotta Creativity Going On: 60 Fun and Unusual Exercises to Awaken and Strengthen Your Creativity', "What's It Like in Space?: Stories from Astronauts Who've Been There", 'We Are Robin, Vol. 1: The Vigilante Business (We Are Robin #1)', "Walt Disney's Alice in Wonderland", 'V for Vendetta (V for Vendetta Complete)', 'Until Friday Night (The Field Party #1)', 'Unbroken: A World War II Story of Survival, Resilience, and Redemption', 'Twenty Yawns', 'Through the Woods', 'This Is Where It Ends', 'The Year of Magical Thinking', 'The Wright Brothers', "The White Queen (The Cousins' War #1)", "The Wedding Pact (The O'Malleys #2)", 'The Time Keeper', 'The Testament of Mary', 'The Star-Touched Queen', 'The Songs of the Gods', 'The Song of Achilles', 'The Rosie Project (Don Tillman #1)', 'The Power of Habit: Why We Do What We Do in Life and Business', 'The Marriage of Opposites', 'The Lucifer Effect: Understanding How Good People Turn Evil', 'The Long Haul (Diary of a Wimpy Kid #9)', 'The Loney', 'The Literature Book (Big Ideas Simply Explained)', 'The Last Mile (Amos Decker #2)', 'The Immortal Life of Henrietta Lacks', 'The Hidden Oracle (The Trials of Apollo #1)', 'The Help Yourself Cookbook for Kids: 60 Easy Plant-Based Recipes Kids Can Make to Stay Healthy and Save the Earth', 'The Guilty (Will Robie #4)', 'The First Hostage (J.B. Collins #2)', 'The Dovekeepers', 'The Darkest Lie', 'The Bane Chronicles (The Bane Chronicles #1-11)', 'The Bad-Ass Librarians of Timbuktu: And Their Race to Save the Worldâ\x80\x99s Most Precious Manuscripts', 'The 14th Colony (Cotton Malone #11)', 'That Darkness (Gardiner and Renner #1)', 'Tastes Like Fear (DI Marnie Rome #3)', 'Take Me with You', 'Swell: A Year of Waves', 'Superman Vol. 1: Before Truth (Superman by Gene Luen Yang #1)', 'Still Life with Bread Crumbs', 'Steve Jobs', 'Sorting the Beef from the Bull: The Science of Food Fraud Forensics', 'Someone Like You (The Harrisons #2)', 'So Cute It Hurts!!, Vol. 6 (So Cute It Hurts!! #6)', 'Shtum', 'See America: A Celebration of Our National Parks & Treasured Sites', 'salt.', 'Robin War', 'Red Hood/Arsenal, Vol. 1: Open for Business (Red Hood/Arsenal #1)', 'Rain Fish', 'Quarter Life Poetry: Poems for the Young, Broke and Hangry', 'Pet Sematary', 'Overload: How to Unplug, Unwind, and Unleash Yourself from the Pressure of Stress', 'Once Was a Time', 'Old School (Diary of a Wimpy Kid #10)', 'No Dream Is Too High: Life Lessons From a Man Who Walked on the Moon', 'Naruto (3-in-1 Edition), Vol. 14: Includes Vols. 40, 41 & 42 (Naruto: Omnibus #14)', 'My Name Is Lucy Barton', 'My Mrs. Brown', 'My Kind of Crazy', 'Mr. Mercedes (Bill Hodges Trilogy #1)', 'More Than Music (Chasing the Dream #1)', 'Made to Stick: Why Some Ideas Survive and Others Die', 'Luis Paints the World', 'Luckiest Girl Alive', 'Lowriders to the Center of the Earth (Lowriders in Space #2)', 'Love Is a Mix Tape (Music #1)', 'Looking for Lovely: Collecting the Moments that Matter', 'Living Leadership by Insight: A Good Leader Achieves, a Great Leader Builds Monuments', 'Let It Out: A Journey Through Journaling', 'Lady Midnight (The Dark Artifices #1)', "It's All Easy: Healthy, Delicious Weeknight Meals in under 30 Minutes", 'Island of Dragons (Unwanteds #7)', "I Know What I'm Doing -- and Other Lies I Tell Myself: Dispatches from a Life Under Construction", 'I Am Pilgrim (Pilgrim #1)', 'Hyperbole and a Half: Unfortunate Situations, Flawed Coping Mechanisms, Mayhem, and Other Things That Happened', 'Hush, Hush (Hush, Hush #1)', 'Hold Your Breath (Search and Rescue #1)', 'Hamilton: The Revolution', 'Greek Mythic History', 'God: The Most Unpleasant Character in All Fiction', 'Glory over Everything: Beyond The Kitchen House', 'Feathers: Displays of Brilliant Plumage', 'Far & Away: Places on the Brink of Change: Seven Continents, Twenty-Five Years', 'Every Last Word', 'Eligible (The Austen Project #4)', 'El Deafo', 'Eight Hundred Grapes', 'Eaternity: More than 150 Deliciously Easy Vegan Recipes for a Long, Healthy, Satisfied, Joyful Life', 'Eat Fat, Get Thin', "Don't Get Caught", 'Doctor Sleep (The Shining #2)', 'Demigods & Magicians: Percy and Annabeth Meet the Kanes (Percy Jackson & Kane Chronicles Crossover #1-3)', 'Dear Mr. Knightley', 'Daily Fantasy Sports', 'Crazy Love: Overwhelmed by a Relentless God', 'Cometh the Hour (The Clifton Chronicles #6)', 'Code Name Verity (Code Name Verity #1)', 'Clockwork Angel (The Infernal Devices #1)', 'City of Glass (The Mortal Instruments #3)', 'City of Fallen Angels (The Mortal Instruments #4)', 'City of Bones (The Mortal Instruments #1)', 'City of Ashes (The Mortal Instruments #2)', 'Cell', 'Catching Jordan (Hundred Oaks)', 'Carry On, Warrior: Thoughts on Life Unarmed', 'Carrie', 'Buying In: The Secret Dialogue Between What We Buy and Who We Are', 'Brain on Fire: My Month of Madness', 'Batman: Europa', 'Barefoot Contessa Back to Basics', "Barefoot Contessa at Home: Everyday Recipes You'll Make Over and Over Again", 'Balloon Animals', 'Art Ops Vol. 1', 'Aristotle and Dante Discover the Secrets of the Universe (Aristotle and Dante Discover the Secrets of the Universe #1)', 'Angels Walking (Angels Walking #1)', 'Angels & Demons (Robert Langdon #1)', 'All the Light We Cannot See', 'Adulthood Is a Myth: A "Sarah\'s Scribbles" Collection', 'Abstract City', 'A Time of Torment (Charlie Parker #14)', 'A Study in Scarlet (Sherlock Holmes #1)', 'A Series of Catastrophes and Miracles: A True Story of Love, Science, and Cancer', "A People's History of the United States", 'A Man Called Ove', 'A Distant Mirror: The Calamitous 14th Century', 'A Brush of Wings (Angels Walking #3)', '1491: New Revelations of the Americas Before Columbus', 'The Three Searches, Meaning, and the Story', 'Searching for Meaning in Gailana', 'Rook', 'My Kitchen Year: 136 Recipes That Saved My Life', '13 Hours: The Inside Account of What Really Happened In Benghazi', "Will You Won't You Want Me?", 'Tipping Point for Planet Earth: How Close Are We to the Edge?', 'The Star-Touched Queen', 'The Silent Sister (Riley MacPherson #1)', 'The Midnight Watch: A Novel of the Titanic and the Californian', 'The Lonely City: Adventures in the Art of Being Alone', 'The Gray Rhino: How to Recognize and Act on the Obvious Dangers We Ignore', 'The Golden Condom: And Other Essays on Love Lost and Found', 'The Epidemic (The Program 0.6)', 'The Dinner Party', 'The Diary of a Young Girl', 'The Children', 'Stars Above (The Lunar Chronicles #4.5)', 'Snatched: How A Drug Queen Went Undercover for the DEA and Was Kidnapped By Colombian Guerillas', 'Raspberry Pi Electronics Projects for the Evil Genius', 'Quench Your Own Thirst: Business Lessons Learned Over a Beer or Two', 'Psycho: Sanitarium (Psycho #1.5)', 'Poisonous (Max Revere Novels #3)', 'One with You (Crossfire #5)', 'No Love Allowed (Dodge Cove #1)', 'Murder at the 42nd Street Library (Raymond Ambler #1)', 'Most Wanted', 'Love, Lies and Spies', 'How to Speak Golf: An Illustrated Guide to Links Lingo', 'Hide Away (Eve Duncan #20)', 'Furiously Happy: A Funny Book About Horrible Things', 'Everyday Italian: 125 Simple and Delicious Recipes', "Equal Is Unfair: America's Misguided Fight Against Income Inequality", 'Eleanor & Park', 'Dirty (Dive Bar #1)', 'Can You Keep a Secret? (Fear Street Relaunch #4)', 'Boar Island (Anna Pigeon #19)', 'A Paris Apartment', 'A la Mode: 120 Recipes in 60 Pairings: Pies, Tarts, Cakes, Crisps, and More Topped with Ice Cream, Gelato, Frozen Custard, and More', 'Troublemaker: Surviving Hollywood and Scientology', 'The Widow', 'The Sleep Revolution: Transforming Your Life, One Night at a Time', 'The Improbability of Love', 'The Art of Startup Fundraising', 'Take Me Home Tonight (Rock Star Romance #3)', 'Sleeping Giants (Themis Files #1)', 'Setting the World on Fire: The Brief, Astonishing Life of St. Catherine of Siena', 'Playing with Fire', 'Off the Hook (Fishing for Trouble #1)', 'Mothering Sunday', 'Mother, Can You Not?', 'M Train', 'Lilac Girls', 'Lies and Other Acts of Love', 'Lab Girl', 'Keep Me Posted', "It Didn't Start with You: How Inherited Family Trauma Shapes Who We Are and How to End the Cycle", 'Grey (Fifty Shades #4)', 'Exit, Pursued by a Bear', 'Daredevils', 'Cravings: Recipes for What You Want to Eat', 'Born for This: How to Find the Work You Were Meant to Do', 'Arena', 'Adultery', "A Mother's Reckoning: Living in the Aftermath of Tragedy", "A Gentleman's Position (Society of Gentlemen #3)", '11/22/63', '10% Happier: How I Tamed the Voice in My Head, Reduced Stress Without Losing My Edge, and Found Self-Help That Actually Works', '10-Day Green Smoothie Cleanse: Lose Up to 15 Pounds in 10 Days!', 'Without Shame', 'Watchmen', 'Unlimited Intuition Now', 'Underlying Notes', 'The Shack', 'The New Brand You: Your New Image Makes the Sale for You', 'The Moosewood Cookbook: Recipes from Moosewood Restaurant, Ithaca, New York', 'The Flowers Lied', 'The Fabric of the Cosmos: Space, Time, and the Texture of Reality', 'The Book of Mormon', 'The Art and Science of Low Carbohydrate Living', 'The Alien Club', 'Suzie Snowflake: One beautiful flake (a self-esteem story)', 'Nap-a-Roo', 'NaNo What Now? Finding your editing process, revising your NaNoWriMo book and building a writing career through publishing and beyond', 'Modern Day Fables', "If I Gave You God's Phone Number....: Searching for Spirituality in America", 'Fruits Basket, Vol. 9 (Fruits Basket

In [4]:
products = {"Title":title,"Prices":price,"Ratings":rating,"stock":stock}
products_df = pd.DataFrame(products)
products_df

,Title,Prices,Ratings,stock
0,A Light in the Attic,£51.77,Three,In stock
1,Tipping the Velvet,£53.74,One,In stock
2,Soumission,£50.10,One,In stock
3,Sharp Objects,£47.82,Four,In stock
4,Sapiens: A Brief History of Humankind,£54.23,Five,In stock
...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,£55.53,One,In stock
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",£57.06,Four,In stock
997,A Spy's Devotion (The Regency Spies of London #1),£16.97,Five,In stock
998,1st to Die (Women's Murder Club #1),£53.98,One,In stock
999,"1,000 Places to See Before You Die",£26.08,Five,In stock

In [13]:
products_df.to_csv(r"C:\Users\pc\Desktop\Python\Books_dataset.csv",index = False)

In [14]:
products_df

,Title,Prices,Ratings,stock
0,A Light in the Attic,£51.77,Three,In stock
1,Tipping the Velvet,£53.74,One,In stock
2,Soumission,£50.10,One,In stock
3,Sharp Objects,£47.82,Four,In stock
4,Sapiens: A Brief History of Humankind,£54.23,Five,In stock
...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,£55.53,One,In stock
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",£57.06,Four,In stock
997,A Spy's Devotion (The Regency Spies of London #1),£16.97,Five,In stock
998,1st to Die (Women's Murder Club #1),£53.98,One,In stock
999,"1,000 Places to See Before You Die",£26.08,Five,In stock